import "./globals.css";
import { Poppins } from "next/font/google";
import Link from "next/link";

const poppins = Poppins({ subsets: ["latin"], weight: ["300", "600"] });

export const metadata = {
  title: "Qui Nguyen's Portfolio Website",
  description: "Generated by create next app",
  keywords: [
    "Developer Portfolio",
    "NextJS",
    "TailwindCSS",
    "TypeScript",
    "Mobile Development",
    "Web Development",
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.className}>
      <body className="flex h-screen flex-col bg-black text-white">
        <main className="min-h-screen">{children}</main>
        <nav className="absolute bottom-0 left-1/2 w-11/12 -translate-x-1/2 -translate-y-1/2 transform border-t border-white">
          <ul className="flex justify-center space-x-24 py-6">
            <li>
              <Link href="/intro">INTRO</Link>
            </li>
            <li>
              <Link href="/work">WORK</Link>
            </li>
            <li>
              <Link href="/resume">RESUME</Link>
            </li>
          </ul>
        </nav>
      </body>
    </html>
  );
}
