import "./globals.css";
import { Poppins } from "next/font/google";
import Link from "next/link";

const poppins = Poppins({ subsets: ["latin"], weight: ["300", "600"] });

export const metadata = {
  title: "Qui Nguyen's Portfolio Website",
  description: "Generated by create next app",
  keywords: [
    "Developer Portfolio",
    "NextJS",
    "TailwindCSS",
    "TypeScript",
    "Mobile Development",
    "Web Development",
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.className}>
      <body className="flex h-screen flex-col text-black">
        <main className="flex min-h-screen justify-center">{children}</main>
      </body>
    </html>
  );
}
